export const SERVICE_METADATA_KEY = Symbol('SERVICE_METADATA_KEY');
export const VERSION_METADATA_KEY = Symbol('VERSION_METADATA_KEY');
export const EFFECT_METADATA_KEY = Symbol('EFFECT_METADATA_KEY');
export const METHOD_METADATA_KEY = Symbol('METHOD_METADATA_KEY');
